
version: '3.8'

services:
  virtualebot:
    image: virtualebot:latest
    secrets:
      - openai_api_key
    volumes:
      - .:/app
    command: >
      sh -c "export OPENAI_API_KEY=$$(cat /run/secrets/openai_api_key) && python virtuale_bot.py"
    depends_on:
      - db
    ports:
      - "8080:80"  # Maps port 80 in the container to port 8080 on the host

  db:
    image: sqlite:latest
    volumes:
      - ./database/virtualeStore.db:/data/virtualeStore.db

secrets:
  openai_api_key:
    external: true

